
import { normalize } from './teams.js';
import { fetchRecentEvents } from './sportsdb.js';
import { ELO_RATINGS } from './data/eloRatings.js';
const MAX_GOALS = 7, AVG_GOALS = 1.32, WORLD_AVG_ELO = 1800;
function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
function factorial(n){let r=1; for(let i=2;i<=n;i++) r*=i; return r;}
function poisson(k,l){return (Math.exp(-l)*Math.pow(l,k))/factorial(k);}
function pct(v){return Number((v*100).toFixed(2));}
function competitionWeight(name=''){const n=name.toLowerCase(); if(n.includes('world cup')) return 1.35; if(n.includes('qualification')||n.includes('qualifier')) return 1.22; if(n.includes('euro')||n.includes('copa')||n.includes('africa')||n.includes('asian')||n.includes('concacaf')) return 1.15; if(n.includes('nations league')) return 1.05; if(n.includes('friendly')) return 0.68; return 1.0;}
function inferSide(e, team){const names=[team.name,...team.aliases].map(normalize), h=normalize(e.strHomeTeam||''), a=normalize(e.strAwayTeam||''); if(names.includes(h)||names.some(n=>h.includes(n)||n.includes(h))) return 'home'; if(names.includes(a)||names.some(n=>a.includes(n)||n.includes(a))) return 'away'; return null;}
function parse(events, team){return events.map((e,i)=>{const side=inferSide(e,team), hs=Number(e.intHomeScore), as=Number(e.intAwayScore); if(!side||Number.isNaN(hs)||Number.isNaN(as)) return null; const gf=side==='home'?hs:as, ga=side==='home'?as:hs, opponent=side==='home'?e.strAwayTeam:e.strHomeTeam; return {date:e.dateEvent, competition:e.strLeague||'Partida', homeTeam:e.strHomeTeam, awayTeam:e.strAwayTeam, homeScore:hs, awayScore:as, opponent, side, gf, ga, result:gf>ga?'W':gf===ga?'D':'L', weight:(1/Math.sqrt(i+1))*competitionWeight(e.strLeague||'')};}).filter(Boolean).slice(0,18);}
function teamFromAnyName(name, allTeams){const n=normalize(name||''); return allTeams.find(t=>normalize(t.name)===n||normalize(t.displayName)===n||t.aliases.some(a=>normalize(a)===n));}
function summarize(team, rawEvents, allTeams){const matches=parse(rawEvents,team); let gfW=0,gaW=0,wSum=0,adjustedGfW=0,adjustedGaW=0; for(const m of matches){const opp=teamFromAnyName(m.opponent, allTeams), oppElo=ELO_RATINGS[opp?.name]||WORLD_AVG_ELO, oppFactor=clamp(oppElo/WORLD_AVG_ELO,.75,1.25); gfW+=m.gf*m.weight; gaW+=m.ga*m.weight; adjustedGfW+=(m.gf*oppFactor)*m.weight; adjustedGaW+=(m.ga/oppFactor)*m.weight; wSum+=m.weight;} const wins=matches.filter(m=>m.result==='W').length, draws=matches.filter(m=>m.result==='D').length, losses=matches.filter(m=>m.result==='L').length; return {team,matches,matchCount:matches.length,avgGoalsFor:wSum?gfW/wSum:AVG_GOALS,avgGoalsAgainst:wSum?gaW/wSum:AVG_GOALS,adjustedAttack:wSum?adjustedGfW/wSum:AVG_GOALS,adjustedDefenseConceded:wSum?adjustedGaW/wSum:AVG_GOALS,form:{wins,draws,losses},dataQuality:matches.length>=8?'boa':matches.length>=4?'média':'baixa'};}
function eloFactor(teamA, teamB, venue){const a=ELO_RATINGS[teamA.name]||WORLD_AVG_ELO, b=ELO_RATINGS[teamB.name]||WORLD_AVG_ELO, venueBonus=venue==='home'?55:venue==='away'?-55:0; return clamp(Math.pow(10,(a-b+venueBonus)/900),.72,1.35);}
function matrix(lambdaH, lambdaA, mode='dixon-coles'){let arr=[], total=0; const rho=-0.09; for(let h=0;h<=MAX_GOALS;h++) for(let a=0;a<=MAX_GOALS;a++){let p=poisson(h,lambdaH)*poisson(a,lambdaA); if(mode==='dixon-coles'){if(h===0&&a===0)p*=1-lambdaH*lambdaA*rho; if(h===0&&a===1)p*=1+lambdaH*rho; if(h===1&&a===0)p*=1+lambdaA*rho; if(h===1&&a===1)p*=1-rho;} total+=p; arr.push({home:h,away:a,probability:p});} return arr.map(x=>({...x,probability:x.probability/total})).sort((a,b)=>b.probability-a.probability);}
function outcomes(m){return m.reduce((acc,s)=>{if(s.home>s.away)acc.homeWin+=s.probability; else if(s.home===s.away)acc.draw+=s.probability; else acc.awayWin+=s.probability; return acc;},{homeWin:0,draw:0,awayWin:0});}
function confidence(hs,as){const data=clamp((hs.matchCount+as.matchCount)/24,0,1), quality=(hs.dataQuality==='boa'?.25:.12)+(as.dataQuality==='boa'?.25:.12); return Math.round(clamp(38+data*38+quality*22,20,90));}
export async function predictMatch(homeTeam, awayTeam, options={}, allTeams){const venue=options.venue||'neutral'; const [hd,ad]=await Promise.all([fetchRecentEvents(homeTeam),fetchRecentEvents(awayTeam)]); const hs=summarize(homeTeam,hd.events,allTeams), as=summarize(awayTeam,ad.events,allTeams); const homeExpected=clamp((hs.adjustedAttack*.58+as.adjustedDefenseConceded*.42)*eloFactor(homeTeam,awayTeam,venue),.12,4.8); const awayVenue=venue==='home'?'away':venue==='away'?'home':'neutral'; const awayExpected=clamp((as.adjustedAttack*.58+hs.adjustedDefenseConceded*.42)*eloFactor(awayTeam,homeTeam,awayVenue),.12,4.8); const advanced=matrix(homeExpected,awayExpected,'dixon-coles'), pure=matrix(homeExpected,awayExpected,'poisson'), best=advanced[0], pureBest=pure[0], out=outcomes(advanced); return {version:'0.1.4',model:'Elo + força adversário + recência/competição + Dixon-Coles',source:'TheSportsDB + cache local',venue,homeTeam,awayTeam,elo:{home:ELO_RATINGS[homeTeam.name]||WORLD_AVG_ELO,away:ELO_RATINGS[awayTeam.name]||WORLD_AVG_ELO},expectedGoals:{home:Number(homeExpected.toFixed(2)),away:Number(awayExpected.toFixed(2))},predictedScore:{home:best.home,away:best.away,probability:pct(best.probability)},comparison:{purePoisson:{home:pureBest.home,away:pureBest.away,probability:pct(pureBest.probability)},advanced:{home:best.home,away:best.away,probability:pct(best.probability)}},outcomes:{homeWin:pct(out.homeWin),draw:pct(out.draw),awayWin:pct(out.awayWin)},confidence:confidence(hs,as),topScores:advanced.slice(0,10).map(s=>({home:s.home,away:s.away,probability:pct(s.probability)})),diagnostics:{home:hs,away:as,notes:['v0.1.4 usa cache local, Elo, pesos de competição/recência e ajuste por adversário.','Dixon-Coles corrige a probabilidade dos placares baixos.','Seleções em português e busca manual no frontend, mantendo cálculo automático.']}};}
